/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package penjualan.view;


import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import penjualan.view.transaksiView;
/**
 *
 * @author SMKN 4 Bandung
 */
public class Master extends javax.swing.JFrame {

    /**
     * Creates new form Master
     */
    public Master() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jHome = new javax.swing.JMenu();
        jMaster = new javax.swing.JMenu();
        jBarang = new javax.swing.JMenuItem();
        jPelanggan = new javax.swing.JMenuItem();
        jTransaksi = new javax.swing.JMenu();
        jPembelian = new javax.swing.JMenuItem();
        jLaporan = new javax.swing.JMenu();
        jLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Vintage and Classic Motorcycle Custom Garage Logo.png"))); // NOI18N

        jHome.setText("Home");
        jMenuBar1.add(jHome);

        jMaster.setText("Master");
        jMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMasterActionPerformed(evt);
            }
        });

        jBarang.setText("Barang");
        jBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBarangActionPerformed(evt);
            }
        });
        jMaster.add(jBarang);

        jPelanggan.setText("Pelanggan");
        jPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPelangganActionPerformed(evt);
            }
        });
        jMaster.add(jPelanggan);

        jMenuBar1.add(jMaster);

        jTransaksi.setText("Transaksi");

        jPembelian.setText("Pembelian");
        jPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPembelianActionPerformed(evt);
            }
        });
        jTransaksi.add(jPembelian);

        jMenuBar1.add(jTransaksi);

        jLaporan.setText("Laporan");
        jMenuBar1.add(jLaporan);

        jLogout.setText("Logout");
        jMenuBar1.add(jLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMasterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMasterActionPerformed

    private void jBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBarangActionPerformed
        barangView pv=new barangView ();
        pv.setLocationRelativeTo(null);
        pv.setVisible(true);
    }//GEN-LAST:event_jBarangActionPerformed

    private void jPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPelangganActionPerformed
        pelangganView pv=new pelangganView ();
        pv.setLocationRelativeTo(null);
        pv.setVisible(true);
    }//GEN-LAST:event_jPelangganActionPerformed

    private void jPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPembelianActionPerformed
        transaksiView pv = null;  
        try {
            pv = new transaksiView ();
        } catch (SQLException ex) {
            Logger.getLogger(Master.class.getName()).log(Level.SEVERE, null, ex);
        }
        pv.setLocationRelativeTo(null);
        pv.setVisible(true);
    }//GEN-LAST:event_jPembelianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jBarang;
    private javax.swing.JMenu jHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jLaporan;
    private javax.swing.JMenu jLogout;
    private javax.swing.JMenu jMaster;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jPelanggan;
    private javax.swing.JMenuItem jPembelian;
    private javax.swing.JMenu jTransaksi;
    // End of variables declaration//GEN-END:variables
}
